build:
  maxIssues: 0

exceptions:
  SwallowedException:
    excludes: [ '**/test/**', '**/androidTest/**' ]
  TooGenericExceptionCaught:
    exceptionNames:
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - RuntimeException
      - Throwable
  PrintStackTrace:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  ConstructorParameterNaming:
    excludes: ['**/catalog/**']
performance:
  SpreadOperator:
    active: false

style:
  MaxLineLength:
    maxLineLength: 100
    excludes: ['**/test/**', '**/androidTest/**', '**/catalog/**']
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  ThrowsCount:
    excludes: ['**/catalog/**']
  MagicNumber:
    excludes: ['**/test/**',
               '**/androidTest/**','**/catalog/**']
  ForbiddenComment:
    excludes: ['**/catalog/**']
  ReturnCount:
    excludes: ['**/catalog/**']
  UseCheckOrError:
    excludes: ['**/catalog/**']

complexity: 
  LargeClass:
    excludes: ['**/test/**', '**/androidTest/**']
  LongParameterList:
    excludes: ['**Module.kt', '**Service.kt', '**Repository.kt', '**/test/**', '**/androidTest/**']
  TooManyFunctions:
     excludes: ['**Module.kt', '**Service.kt', '**Repository.kt', '**/test/**',
                '**/androidTest/**', '**/catalog/**']
  CyclomaticComplexMethod:
    excludes: ['**/catalog/**']
  LongMethod:
    excludes: ['**/catalog/**']
  NestedBlockDepth:
    excludes: [ '**/catalog/**' ]
