additionalProperties:
  artifactId: catalogue.generated
  packageName: com.tidal.sdk.catalogue.generated
  apiSuffix: ''
  dateLibrary: java8
  groupId: com.tidal.sdk
  library: jvm-retrofit2
  serializationLibrary: kotlinx_serialization
  supportAndroidApiLevel25AndBelow: true
  useCoroutines: true
