/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.apis.AlbumJSONAPIApi
import com.tidal.sdk.catalog.models.AlbumDataDocument
import com.tidal.sdk.catalog.models.AlbumRelationshipsDocument
import com.tidal.sdk.catalog.models.AlbumsDataDocument
import com.tidal.sdk.catalog.models.ErrorDocument

class AlbumJSONAPIApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AlbumJSONAPIApi
        //val apiInstance = AlbumJSONAPIApi()

        // to test getAlbum
        should("test getAlbum") {
            // uncomment below to test getAlbum
            //val id : kotlin.String = 251380836 // kotlin.String | TIDAL album id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: artists, items, providers, similarAlbums
            //val result : AlbumDataDocument = apiInstance.getAlbum(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getAlbumArtists
        should("test getAlbumArtists") {
            // uncomment below to test getAlbumArtists
            //val id : kotlin.String = 251380836 // kotlin.String | TIDAL album id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: artists
            //val result : AlbumRelationshipsDocument = apiInstance.getAlbumArtists(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getAlbumItems
        should("test getAlbumItems") {
            // uncomment below to test getAlbumItems
            //val id : kotlin.String = 251380836 // kotlin.String | TIDAL album id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: items
            //val result : AlbumRelationshipsDocument = apiInstance.getAlbumItems(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getAlbumProviders
        should("test getAlbumProviders") {
            // uncomment below to test getAlbumProviders
            //val id : kotlin.String = 251380836 // kotlin.String | TIDAL id of the album
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: providers
            //val result : AlbumRelationshipsDocument = apiInstance.getAlbumProviders(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getAlbums
        should("test getAlbums") {
            // uncomment below to test getAlbums
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: artists, items, providers, similarAlbums
            //val filterId : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows to filter the collection of resources based on id attribute value
            //val filterBarcodeId : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows to filter the collection of resources based on barcodeId attribute value
            //val result : AlbumsDataDocument = apiInstance.getAlbums(countryCode, include, filterId, filterBarcodeId)
            //result shouldBe ("TODO")
        }

        // to test getSimilarAlbums1
        should("test getSimilarAlbums1") {
            // uncomment below to test getSimilarAlbums1
            //val id : kotlin.String = 251380836 // kotlin.String | TIDAL id of the album
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: similarAlbums
            //val result : AlbumRelationshipsDocument = apiInstance.getSimilarAlbums1(id, countryCode, include)
            //result shouldBe ("TODO")
        }

    }
}
