/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.apis.ArtistJSONAPIApi
import com.tidal.sdk.catalog.models.ArtistDataDocument
import com.tidal.sdk.catalog.models.ArtistRelationshipsDocument
import com.tidal.sdk.catalog.models.ArtistsDataDocument
import com.tidal.sdk.catalog.models.ErrorDocument

class ArtistJSONAPIApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ArtistJSONAPIApi
        //val apiInstance = ArtistJSONAPIApi()

        // to test getArtist
        should("test getArtist") {
            // uncomment below to test getArtist
            //val id : kotlin.String = 1566 // kotlin.String | TIDAL artist id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: albums, tracks, videos, similarArtists
            //val result : ArtistDataDocument = apiInstance.getArtist(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getArtistAlbums
        should("test getArtistAlbums") {
            // uncomment below to test getArtistAlbums
            //val id : kotlin.String = 1566 // kotlin.String | TIDAL artist id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: albums
            //val result : ArtistRelationshipsDocument = apiInstance.getArtistAlbums(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getArtistTracks
        should("test getArtistTracks") {
            // uncomment below to test getArtistTracks
            //val id : kotlin.String = 1566 // kotlin.String | TIDAL artist id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: tracks
            //val result : ArtistRelationshipsDocument = apiInstance.getArtistTracks(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getArtistVideos
        should("test getArtistVideos") {
            // uncomment below to test getArtistVideos
            //val id : kotlin.String = 1566 // kotlin.String | TIDAL artist id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: videos
            //val result : ArtistRelationshipsDocument = apiInstance.getArtistVideos(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getArtists
        should("test getArtists") {
            // uncomment below to test getArtists
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: albums, tracks, videos, similarArtists
            //val filterId : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows to filter the collection of resources based on id attribute value
            //val result : ArtistsDataDocument = apiInstance.getArtists(countryCode, include, filterId)
            //result shouldBe ("TODO")
        }

        // to test getSimilarArtists
        should("test getSimilarArtists") {
            // uncomment below to test getSimilarArtists
            //val id : kotlin.String = 1566 // kotlin.String | TIDAL id of the artist
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: similarArtists
            //val result : ArtistRelationshipsDocument = apiInstance.getSimilarArtists(id, countryCode, include)
            //result shouldBe ("TODO")
        }

    }
}
