/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.apis.ProviderJSONAPIApi
import com.tidal.sdk.catalog.models.ErrorDocument
import com.tidal.sdk.catalog.models.ProviderDataDocument
import com.tidal.sdk.catalog.models.ProvidersDataDocument

class ProviderJSONAPIApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProviderJSONAPIApi
        //val apiInstance = ProviderJSONAPIApi()

        // to test getProvider
        should("test getProvider") {
            // uncomment below to test getProvider
            //val id : kotlin.String = 771 // kotlin.String | TIDAL provider id
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned
            //val result : ProviderDataDocument = apiInstance.getProvider(id, include)
            //result shouldBe ("TODO")
        }

        // to test getProviders
        should("test getProviders") {
            // uncomment below to test getProviders
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned
            //val filterId : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows to filter the collection of resources based on id attribute value
            //val result : ProvidersDataDocument = apiInstance.getProviders(include, filterId)
            //result shouldBe ("TODO")
        }

    }
}
