/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.apis.TrackJSONAPIApi
import com.tidal.sdk.catalog.models.ErrorDocument
import com.tidal.sdk.catalog.models.TrackDataDocument
import com.tidal.sdk.catalog.models.TrackRelationshipsDocument
import com.tidal.sdk.catalog.models.TracksDataDocument

class TrackJSONAPIApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrackJSONAPIApi
        //val apiInstance = TrackJSONAPIApi()

        // to test getSimilarAlbums
        should("test getSimilarAlbums") {
            // uncomment below to test getSimilarAlbums
            //val id : kotlin.String = 251380837 // kotlin.String | TIDAL id of the track
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: similarTracks
            //val result : TrackRelationshipsDocument = apiInstance.getSimilarAlbums(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getTrack
        should("test getTrack") {
            // uncomment below to test getTrack
            //val id : kotlin.String = 251380837 // kotlin.String | TIDAL track id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: artists, albums, providers, similarTracks
            //val result : TrackDataDocument = apiInstance.getTrack(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getTrackAlbums
        should("test getTrackAlbums") {
            // uncomment below to test getTrackAlbums
            //val id : kotlin.String = 251380837 // kotlin.String | TIDAL track id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: albums
            //val result : TrackRelationshipsDocument = apiInstance.getTrackAlbums(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getTrackArtists
        should("test getTrackArtists") {
            // uncomment below to test getTrackArtists
            //val id : kotlin.String = 251380837 // kotlin.String | TIDAL track id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: artists
            //val result : TrackRelationshipsDocument = apiInstance.getTrackArtists(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getTrackProviders
        should("test getTrackProviders") {
            // uncomment below to test getTrackProviders
            //val id : kotlin.String = 251380837 // kotlin.String | TIDAL id of the track
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: providers
            //val result : TrackRelationshipsDocument = apiInstance.getTrackProviders(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getTracks
        should("test getTracks") {
            // uncomment below to test getTracks
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: artists, albums, providers, similarTracks
            //val filterId : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows to filter the collection of resources based on id attribute value
            //val filterIsrc : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows to filter the collection of resources based on isrc attribute value
            //val result : TracksDataDocument = apiInstance.getTracks(countryCode, include, filterId, filterIsrc)
            //result shouldBe ("TODO")
        }

    }
}
