/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import generated.org.openapitools.client.apis.VideoJSONAPIApi
import generated.org.openapitools.client.models.ErrorDocument
import generated.org.openapitools.client.models.VideoDataDocument
import generated.org.openapitools.client.models.VideoRelationshipsDocument
import generated.org.openapitools.client.models.VideosDataDocument

class VideoJSONAPIApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VideoJSONAPIApi
        //val apiInstance = VideoJSONAPIApi()

        // to test getVideo
        should("test getVideo") {
            // uncomment below to test getVideo
            //val id : kotlin.String = 75623239 // kotlin.String | TIDAL video id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: artists, albums, providers
            //val result : VideoDataDocument = apiInstance.getVideo(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getVideoAlbums
        should("test getVideoAlbums") {
            // uncomment below to test getVideoAlbums
            //val id : kotlin.String = 75623239 // kotlin.String | TIDAL video id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: albums
            //val result : VideoRelationshipsDocument = apiInstance.getVideoAlbums(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getVideoArtists
        should("test getVideoArtists") {
            // uncomment below to test getVideoArtists
            //val id : kotlin.String = 75623239 // kotlin.String | TIDAL video id
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: artists
            //val result : VideoRelationshipsDocument = apiInstance.getVideoArtists(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getVideoProviders
        should("test getVideoProviders") {
            // uncomment below to test getVideoProviders
            //val id : kotlin.String = 75623239 // kotlin.String | TIDAL id of the video
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: providers
            //val result : VideoRelationshipsDocument = apiInstance.getVideoProviders(id, countryCode, include)
            //result shouldBe ("TODO")
        }

        // to test getVideos
        should("test getVideos") {
            // uncomment below to test getVideos
            //val countryCode : kotlin.String = US // kotlin.String | ISO 3166-1 alpha-2 country code
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows the client to customize which related resources should be returned. Available options: artists, albums, providers
            //val filterId : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows to filter the collection of resources based on id attribute value
            //val filterIsrc : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Allows to filter the collection of resources based on isrc attribute value
            //val result : VideosDataDocument = apiInstance.getVideos(countryCode, include, filterId, filterIsrc)
            //result shouldBe ("TODO")
        }

    }
}
