package com.tidal.sdk.player.streamingapi.drm.model

import androidx.annotation.Keep
import com.tidal.sdk.player.streamingapi.playbackinfo.model.PlaybackInfo

/**
 * Drm license request of a given track or video. This will be the request we send to our backend
 * and it will be used to retrieve a [DrmLicense].
 *
 * @property[streamingSessionId] A uuid generated by the client for this streaming session.
 * @property[securityToken] The license security token from [PlaybackInfo].
 * @property[payload] Base64 encoded payload from the CDM.
 */
@Keep
data class DrmLicenseRequest(
    val streamingSessionId: String,
    val securityToken: String,
    val payload: String,
)
