package com.tidal.sdk.player.streamingapi

object ApiConstants {

    const val TRACKS_PATH = "playbackinfo/tracks/get_1"
    const val VIDEOS_PATH = "playbackinfo/videos/get_1"
    const val LICENSE_PATH = "drm/licenses/widevine/post"
    const val LICENSE_URL = "licenseUrl"

    const val PLAYBACK_INFO_ID_FOR_DEFAULT = "1"
    const val PLAYBACK_INFO_ID_FOR_DEFAULT_2 = "2"

    const val MANIFEST =
        "PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRGLTgnPz48TVBEIHhtbG5zPSJ1cm46bXBlZzpkYXNo" +
            "OnNjaGVtYTptcGQ6MjAxMSIgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVt" +
            "YS1pbnN0YW5jZSIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHhtbG5z" +
            "OmNlbmM9InVybjptcGVnOmNlbmM6MjAxMyIgeHNpOnNjaGVtYUxvY2F0aW9uPSJ1cm46bXBlZzpkYXNo" +
            "OnNjaGVtYTptcGQ6MjAxMSBEQVNILU1QRC54c2QiIHByb2ZpbGVzPSJ1cm46bXBlZzpkYXNoOnByb2Zp" +
            "bGU6aXNvZmYtbWFpbjoyMDExIiB0eXBlPSJzdGF0aWMiIG1pbkJ1ZmZlclRpbWU9IlBUMy45OTNTIiBt" +
            "ZWRpYVByZXNlbnRhdGlvbkR1cmF0aW9uPSJQVDNNNTAuODYxUyI+PFBlcmlvZCBpZD0iMCI+PEFkYXB0" +
            "YXRpb25TZXQgaWQ9IjAiIGNvbnRlbnRUeXBlPSJhdWRpbyIgbWltZVR5cGU9ImF1ZGlvL21wNCIgc2Vn" +
            "bWVudEFsaWdubWVudD0idHJ1ZSI+PFJlcHJlc2VudGF0aW9uIGlkPSIwIiBjb2RlY3M9Im1wNGEuNDAu" +
            "NSIgYmFuZHdpZHRoPSI5Njk4MiIgYXVkaW9TYW1wbGluZ1JhdGU9IjQ0MTAwIj48U2VnbWVudFRlbXBs" +
            "YXRlIHRpbWVzY2FsZT0iNDQxMDAiIGluaXRpYWxpemF0aW9uPSJodHRwczovL3NwLWFkLWZhLmF1ZGlv" +
            "LnRpZGFsLmNvbS9tZWRpYXRyYWNrcy9HaWtTSjJZME16azNaV1ZtTkdWaFlUZG1PV0V4T1daa1l6TmtP" +
            "RGc1WXpObE1qVXpYek0yTG0xd05DSWJIUUFBZ0VBZ0Fpb1FtMGItQnBHVk5xQzU5VVozR0w2ai16SUEv" +
            "MC5tcDQ/dG9rZW49MTYzODk3NjU5OX5MMjFsWkdsaGRISmhZMnR6TDBkcGExTktNbGt3VFhwck0xcFhW" +
            "bTFPUjFab1dWUmtiVTlYUlhoUFYxcHJXWHBPYTA5RVp6VlplazVzVFdwVmVsaDZUVEpNYlRGM1RrTkpZ" +
            "a2hSUVVGblJVRm5RV2x2VVcwd1lpMUNjRWRXVG5GRE5UbFZXak5IVERacUxYcEpRUzhxZmpKa01UVTNZ" +
            "V00yTXprd09HWm1ZMkl4TmpVd016SXlZbUl5TmpJek9URmhZMkkzTW1FMlpUVT0iIG1lZGlhPSJodHRw" +
            "czovL3NwLWFkLWZhLmF1ZGlvLnRpZGFsLmNvbS9tZWRpYXRyYWNrcy9HaWtTSjJZME16azNaV1ZtTkdW" +
            "aFlUZG1PV0V4T1daa1l6TmtPRGc1WXpObE1qVXpYek0yTG0xd05DSWJIUUFBZ0VBZ0Fpb1FtMGItQnBH" +
            "Vk5xQzU5VVozR0w2ai16SUEvJE51bWJlciQubXA0P3Rva2VuPTE2Mzg5NzY1OTl+TDIxbFpHbGhkSEpo" +
            "WTJ0ekwwZHBhMU5LTWxrd1RYcHJNMXBYVm0xT1IxWm9XVlJrYlU5WFJYaFBWMXByV1hwT2EwOUVaelZa" +
            "ZWs1c1RXcFZlbGg2VFRKTWJURjNUa05KWWtoUlFVRm5SVUZuUVdsdlVXMHdZaTFDY0VkV1RuRkROVGxW" +
            "V2pOSFREWnFMWHBKUVM4cWZqSmtNVFUzWVdNMk16a3dPR1ptWTJJeE5qVXdNekl5WW1JeU5qSXpPVEZo" +
            "WTJJM01tRTJaVFU9IiBzdGFydE51bWJlcj0iMSI+PFNlZ21lbnRUaW1lbGluZT48UyBkPSIxNzYxMjgi" +
            "IHI9IjU2Ii8+PFMgZD0iMTQxNjkwIi8+PC9TZWdtZW50VGltZWxpbmU+PC9TZWdtZW50VGVtcGxhdGU+" +
            "PC9SZXByZXNlbnRhdGlvbj48L0FkYXB0YXRpb25TZXQ+PC9QZXJpb2Q+PC9NUEQ+"
    const val MANIFEST_HASH = "CtNeaqTb1Oo+7XOkJC6ixSYqniB23kxfHPWMX5hAYSo="
    const val MANIFEST_DJ_SESSION =
        "eyJtaW1lVHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5hcHBsZS5tcGVndXJs" +
            "IiwidXJscyI6WyJodHRwczovL2ltLWZhLm1hbmlmZXN0LnRpZGFsLmNvbS8wL2Jyb2FkY2FzdHMvbWFuaWZl" +
            "c3RzL0Vob3dNVWd6UkVOQk1VTllNMGRSVkZGSFUwNUxOMHBFV1ZrM05DQUNLZ2x0Y0RSaExqUXdMalV3QVRn" +
            "Q1FnSlZVdy5tM3U4P3Rva2VuPTE2ODczNjk5NTh+T1RRMVpERTVOR1F3TlRJNVpqRXhNakU1Tm1GbVpqSXhP" +
            "VFF3T0dVeE56STROalZoWmpJM09RPT0iXX0="

    val DRM_PAYLOAD_REQUEST = "payload".toByteArray()
    const val DRM_PAYLOAD_RESPONSE =
        "CAIS0wIKVAogMjAzNkVDNUJBNDIzQkU5N0Y2MDIwMDAwMDAwMDAwMDA" +
            "SIDIwMzZFQzVCQTQyM0JFOTdGNjAyMDAwMDAwMDAwMDAwGgAgASgAOABAAEjo1c+PBhICCAEaZhIQWO15WFI" +
            "HzJPSCxPyL+zNixpQHoajI22IArbGssE57AjaUfBX+mdfS5z4RqdSBJy7DgCNFQaYjCxx1j2VW+eNLfesLY2" +
            "cKUq6rCKofshl/7kvxItOC+AZSwACcVSG0XmHftsgARqCAQoQA/rlaIqO0TSPE6fUyEjztxIQSl4mNGVYfsc" +
            "x+qApLj88whogX6E1Bvr0ZE5B85lGPSyTk/ryJAAaI0C1UlGA6q6ieGUgAigBQjQKIAKx1CXh0wKxKgHGK22" +
            "CZAmYMOnhRmgTlwQrSfm8nHvmEhCbYJjtIEhRudo9GKcNBhosYgAg6NXPjwY488aJmwYaILBy67z2nTEDWzL" +
            "7pFK+Yl0u39weTyXo71jpz0uGcMRDIoACCVEb5lx7A3Dsu0QwtVaGX8RSgHRuHw/9yxBaQYnIM5sURhK2Q5C" +
            "U9wsaN2jzse+C9hk1ZTSjFOK0JtcoblE3/BS7GCpCR6V+HXk4MvNBjf+b8ofWPv/s0swsV7YSiq05fmjWOLt" +
            "2Nfoi0u8GQw9MxXsfdnUuK4E7fdyD6gCOv1djk/JR2Jf+7yxjfPbNVocrN38EixmfPS1CH7WAaEzPhkKdSXS" +
            "uTZYSQS1CTU3RqG7dneevNfzgJwxl20U3J+R6aL+0lHXGehMqV5Hca70uYyzUCPaHFOhjnA5TsMDNG3A+BWj" +
            "9kxskdBJ1M2Atnuy7ngjZKw2uojui+wMzcGEX1DozCjExNi41LjAgQnVpbHQgb24gRGVjIDE1IDIwMjEgMTA" +
            "6Mjc6MTcgKDE2Mzk1OTI4MTUpQAFKsAEAAAACAAAAsAAEABDj/RKqAAAAAAAAAF4AAAAQAAAAcAAAAFAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAQAAAMcAAAAQAAAA2QAAABAAAADrAAAAEAAAATUAAAAQAAABEwAAACA3efvTO1lVclp+lMcjOIQ3qmaf9Ki" +
            "TTdMp5y7nlPkE2VgA"

    const val OFFLINE_REVALIDATE_AT_SECONDS = 1641113514L
    const val OFFLINE_VALID_UNTIL_SECONDS = 1641718314L

    const val STREAMING_SESSION_ID = "123-abc"
}
