/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.apis

import com.tidal.sdk.catalog.infrastructure.ApiClient
import com.tidal.sdk.catalog.infrastructure.ApiResponse
import com.tidal.sdk.catalog.infrastructure.ClientError
import com.tidal.sdk.catalog.infrastructure.ClientException
import com.tidal.sdk.catalog.infrastructure.MultiValueMap
import com.tidal.sdk.catalog.infrastructure.RequestConfig
import com.tidal.sdk.catalog.infrastructure.RequestMethod
import com.tidal.sdk.catalog.infrastructure.ResponseType
import com.tidal.sdk.catalog.infrastructure.ServerError
import com.tidal.sdk.catalog.infrastructure.ServerException
import com.tidal.sdk.catalog.infrastructure.Success
import com.tidal.sdk.catalog.infrastructure.toMultiValue
import com.tidal.sdk.catalog.models.ArtistDataDocument
import com.tidal.sdk.catalog.models.ArtistRelationshipsDocument
import com.tidal.sdk.catalog.models.ArtistsDataDocument
import okhttp3.HttpUrl
import okhttp3.OkHttpClient
import java.io.IOException

class ArtistJSONAPIApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://openapi.stage.tidal.com/v2")
        }
    }

    /**
     * Get single artist
     * Retrieve artist details by TIDAL artist id.
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: albums, tracks, videos, similarArtists (optional)
     * @return ArtistDataDocument
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getArtist(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>? = null) : ArtistDataDocument {
        val localVarResponse = getArtistWithHttpInfo(id = id, countryCode = countryCode, include = include)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ArtistDataDocument
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get single artist
     * Retrieve artist details by TIDAL artist id.
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: albums, tracks, videos, similarArtists (optional)
     * @return ApiResponse<ArtistDataDocument?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getArtistWithHttpInfo(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?) : ApiResponse<ArtistDataDocument?> {
        val localVariableConfig = getArtistRequestConfig(id = id, countryCode = countryCode, include = include)

        return request<Unit, ArtistDataDocument>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getArtist
     *
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: albums, tracks, videos, similarArtists (optional)
     * @return RequestConfig
     */
    fun getArtistRequestConfig(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("countryCode", listOf(countryCode.toString()))
                if (include != null) {
                    put("include", toMultiValue(include.toList(), "multi"))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/vnd.api+json"
        localVariableHeaders["Accept"] = "application/vnd.api+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/artists/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Relationship: albums
     * Retrieve album details of the related artist.
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: albums (optional)
     * @return ArtistRelationshipsDocument
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getArtistAlbums(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>? = null) : ArtistRelationshipsDocument {
        val localVarResponse = getArtistAlbumsWithHttpInfo(id = id, countryCode = countryCode, include = include)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ArtistRelationshipsDocument
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Relationship: albums
     * Retrieve album details of the related artist.
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: albums (optional)
     * @return ApiResponse<ArtistRelationshipsDocument?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getArtistAlbumsWithHttpInfo(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?) : ApiResponse<ArtistRelationshipsDocument?> {
        val localVariableConfig = getArtistAlbumsRequestConfig(id = id, countryCode = countryCode, include = include)

        return request<Unit, ArtistRelationshipsDocument>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getArtistAlbums
     *
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: albums (optional)
     * @return RequestConfig
     */
    fun getArtistAlbumsRequestConfig(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("countryCode", listOf(countryCode.toString()))
                if (include != null) {
                    put("include", toMultiValue(include.toList(), "multi"))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/vnd.api+json"
        localVariableHeaders["Accept"] = "application/vnd.api+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/artists/{id}/relationships/albums".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Relationship: tracks
     * Retrieve track details by related artist.
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: tracks (optional)
     * @return ArtistRelationshipsDocument
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getArtistTracks(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>? = null) : ArtistRelationshipsDocument {
        val localVarResponse = getArtistTracksWithHttpInfo(id = id, countryCode = countryCode, include = include)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ArtistRelationshipsDocument
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Relationship: tracks
     * Retrieve track details by related artist.
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: tracks (optional)
     * @return ApiResponse<ArtistRelationshipsDocument?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getArtistTracksWithHttpInfo(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?) : ApiResponse<ArtistRelationshipsDocument?> {
        val localVariableConfig = getArtistTracksRequestConfig(id = id, countryCode = countryCode, include = include)

        return request<Unit, ArtistRelationshipsDocument>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getArtistTracks
     *
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: tracks (optional)
     * @return RequestConfig
     */
    fun getArtistTracksRequestConfig(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("countryCode", listOf(countryCode.toString()))
                if (include != null) {
                    put("include", toMultiValue(include.toList(), "multi"))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/vnd.api+json"
        localVariableHeaders["Accept"] = "application/vnd.api+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/artists/{id}/relationships/tracks".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Relationship: videos
     * Retrieve video details by related artist.
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: videos (optional)
     * @return ArtistRelationshipsDocument
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getArtistVideos(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>? = null) : ArtistRelationshipsDocument {
        val localVarResponse = getArtistVideosWithHttpInfo(id = id, countryCode = countryCode, include = include)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ArtistRelationshipsDocument
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Relationship: videos
     * Retrieve video details by related artist.
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: videos (optional)
     * @return ApiResponse<ArtistRelationshipsDocument?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getArtistVideosWithHttpInfo(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?) : ApiResponse<ArtistRelationshipsDocument?> {
        val localVariableConfig = getArtistVideosRequestConfig(id = id, countryCode = countryCode, include = include)

        return request<Unit, ArtistRelationshipsDocument>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getArtistVideos
     *
     * @param id TIDAL artist id
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: videos (optional)
     * @return RequestConfig
     */
    fun getArtistVideosRequestConfig(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("countryCode", listOf(countryCode.toString()))
                if (include != null) {
                    put("include", toMultiValue(include.toList(), "multi"))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/vnd.api+json"
        localVariableHeaders["Accept"] = "application/vnd.api+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/artists/{id}/relationships/videos".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get multiple artists
     * Retrieve multiple artist details.
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: albums, tracks, videos, similarArtists (optional)
     * @param filterId Allows to filter the collection of resources based on id attribute value (optional)
     * @return ArtistsDataDocument
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getArtists(countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>? = null, filterId: kotlin.collections.List<kotlin.String>? = null) : ArtistsDataDocument {
        val localVarResponse = getArtistsWithHttpInfo(countryCode = countryCode, include = include, filterId = filterId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ArtistsDataDocument
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get multiple artists
     * Retrieve multiple artist details.
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: albums, tracks, videos, similarArtists (optional)
     * @param filterId Allows to filter the collection of resources based on id attribute value (optional)
     * @return ApiResponse<ArtistsDataDocument?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getArtistsWithHttpInfo(countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?, filterId: kotlin.collections.List<kotlin.String>?) : ApiResponse<ArtistsDataDocument?> {
        val localVariableConfig = getArtistsRequestConfig(countryCode = countryCode, include = include, filterId = filterId)

        return request<Unit, ArtistsDataDocument>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getArtists
     *
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: albums, tracks, videos, similarArtists (optional)
     * @param filterId Allows to filter the collection of resources based on id attribute value (optional)
     * @return RequestConfig
     */
    fun getArtistsRequestConfig(countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?, filterId: kotlin.collections.List<kotlin.String>?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("countryCode", listOf(countryCode.toString()))
                if (include != null) {
                    put("include", toMultiValue(include.toList(), "multi"))
                }
                if (filterId != null) {
                    put("filter[id]", toMultiValue(filterId.toList(), "multi"))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/vnd.api+json"
        localVariableHeaders["Accept"] = "application/vnd.api+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/artists",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Relationship: similar artists
     * This endpoint can be used to retrieve a list of artists similar to the given artist.
     * @param id TIDAL id of the artist
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: similarArtists (optional)
     * @return ArtistRelationshipsDocument
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getSimilarArtists(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>? = null) : ArtistRelationshipsDocument {
        val localVarResponse = getSimilarArtistsWithHttpInfo(id = id, countryCode = countryCode, include = include)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ArtistRelationshipsDocument
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Relationship: similar artists
     * This endpoint can be used to retrieve a list of artists similar to the given artist.
     * @param id TIDAL id of the artist
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: similarArtists (optional)
     * @return ApiResponse<ArtistRelationshipsDocument?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getSimilarArtistsWithHttpInfo(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?) : ApiResponse<ArtistRelationshipsDocument?> {
        val localVariableConfig = getSimilarArtistsRequestConfig(id = id, countryCode = countryCode, include = include)

        return request<Unit, ArtistRelationshipsDocument>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getSimilarArtists
     *
     * @param id TIDAL id of the artist
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @param include Allows the client to customize which related resources should be returned. Available options: similarArtists (optional)
     * @return RequestConfig
     */
    fun getSimilarArtistsRequestConfig(id: kotlin.String, countryCode: kotlin.String, include: kotlin.collections.List<kotlin.String>?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("countryCode", listOf(countryCode.toString()))
                if (include != null) {
                    put("include", toMultiValue(include.toList(), "multi"))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/vnd.api+json"
        localVariableHeaders["Accept"] = "application/vnd.api+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/artists/{id}/relationships/similarArtists".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
