/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.AlbumResource
import com.tidal.sdk.catalog.models.AlbumAttributes
import com.tidal.sdk.catalog.models.AvailableAlbumRelationships
import com.tidal.sdk.catalog.models.Links

class AlbumResourceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AlbumResource
        //val modelInstance = AlbumResource()

        // to test the property `id` - resource unique identifier
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type` - resource unique type
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `attributes`
        should("test attributes") {
            // uncomment below to test the property
            //modelInstance.attributes shouldBe ("TODO")
        }

        // to test the property `relationships`
        should("test relationships") {
            // uncomment below to test the property
            //modelInstance.relationships shouldBe ("TODO")
        }

        // to test the property `links`
        should("test links") {
            // uncomment below to test the property
            //modelInstance.links shouldBe ("TODO")
        }

    }
}
