/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.AlbumAttributes
import com.tidal.sdk.catalog.models.ExternalLink
import com.tidal.sdk.catalog.models.ImageLink
import com.tidal.sdk.catalog.models.VideoLink

class AlbumAttributesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AlbumAttributes
        //val modelInstance = AlbumAttributes()

        // to test the property `title` - Original title
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `barcodeId` - Barcode id (EAN-13 or UPC-A)
        should("test barcodeId") {
            // uncomment below to test the property
            //modelInstance.barcodeId shouldBe ("TODO")
        }

        // to test the property `numberOfVolumes` - Number of volumes
        should("test numberOfVolumes") {
            // uncomment below to test the property
            //modelInstance.numberOfVolumes shouldBe ("TODO")
        }

        // to test the property `numberOfItems` - Number of album items
        should("test numberOfItems") {
            // uncomment below to test the property
            //modelInstance.numberOfItems shouldBe ("TODO")
        }

        // to test the property `duration` - Duration (ISO-8601)
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `explicit` - Indicates whether an album consist of any explicit content
        should("test explicit") {
            // uncomment below to test the property
            //modelInstance.explicit shouldBe ("TODO")
        }

        // to test the property `popularity` - Album popularity (ranged in 0.00 ... 1.00). Conditionally visible
        should("test popularity") {
            // uncomment below to test the property
            //modelInstance.popularity shouldBe ("TODO")
        }

        // to test the property `mediaTags`
        should("test mediaTags") {
            // uncomment below to test the property
            //modelInstance.mediaTags shouldBe ("TODO")
        }

        // to test the property `releaseDate` - Release date (ISO-8601)
        should("test releaseDate") {
            // uncomment below to test the property
            //modelInstance.releaseDate shouldBe ("TODO")
        }

        // to test the property `copyright` - Copyright information
        should("test copyright") {
            // uncomment below to test the property
            //modelInstance.copyright shouldBe ("TODO")
        }

        // to test the property `availability` - Defines an album availability e.g. for streaming, DJs, stems
        should("test availability") {
            // uncomment below to test the property
            //modelInstance.availability shouldBe ("TODO")
        }

        // to test the property `imageLinks` - Represents available links to, and metadata about, an album cover images
        should("test imageLinks") {
            // uncomment below to test the property
            //modelInstance.imageLinks shouldBe ("TODO")
        }

        // to test the property `videoLinks` - Represents available links to, and metadata about, an album cover videos
        should("test videoLinks") {
            // uncomment below to test the property
            //modelInstance.videoLinks shouldBe ("TODO")
        }

        // to test the property `externalLinks` - Represents available links to something that is related to an album resource, but external to the TIDAL API
        should("test externalLinks") {
            // uncomment below to test the property
            //modelInstance.externalLinks shouldBe ("TODO")
        }

    }
}
