/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.ArtistAttributes
import com.tidal.sdk.catalog.models.ExternalLink
import com.tidal.sdk.catalog.models.ImageLink

class ArtistAttributesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ArtistAttributes
        //val modelInstance = ArtistAttributes()

        // to test the property `name` - Artist name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `popularity` - Artist popularity (ranged in 0.00 ... 1.00). Conditionally visible
        should("test popularity") {
            // uncomment below to test the property
            //modelInstance.popularity shouldBe ("TODO")
        }

        // to test the property `imageLinks` - Represents available links to, and metadata about, an artist images
        should("test imageLinks") {
            // uncomment below to test the property
            //modelInstance.imageLinks shouldBe ("TODO")
        }

        // to test the property `externalLinks` - Represents available links to something that is related to an artist resource, but external to the TIDAL API
        should("test externalLinks") {
            // uncomment below to test the property
            //modelInstance.externalLinks shouldBe ("TODO")
        }

    }
}
