/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.AvailableAlbumRelationships
import com.tidal.sdk.catalog.models.AvailableAlbumRelationshipsItems
import com.tidal.sdk.catalog.models.ResourceRelationship

class AvailableAlbumRelationshipsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AvailableAlbumRelationships
        //val modelInstance = AvailableAlbumRelationships()

        // to test the property `artists`
        should("test artists") {
            // uncomment below to test the property
            //modelInstance.artists shouldBe ("TODO")
        }

        // to test the property `similarAlbums`
        should("test similarAlbums") {
            // uncomment below to test the property
            //modelInstance.similarAlbums shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `providers`
        should("test providers") {
            // uncomment below to test the property
            //modelInstance.providers shouldBe ("TODO")
        }

    }
}
