/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import generated.org.openapitools.client.models.AvailableAlbumRelationshipsItemsDataInnerMeta

class AvailableAlbumRelationshipsItemsDataInnerMetaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AvailableAlbumRelationshipsItemsDataInnerMeta
        //val modelInstance = AvailableAlbumRelationshipsItemsDataInnerMeta()

        // to test the property `volumeNumber` - volume number
        should("test volumeNumber") {
            // uncomment below to test the property
            //modelInstance.volumeNumber shouldBe ("TODO")
        }

        // to test the property `trackNumber` - track number
        should("test trackNumber") {
            // uncomment below to test the property
            //modelInstance.trackNumber shouldBe ("TODO")
        }

    }
}
