/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.AvailableArtistRelationships
import com.tidal.sdk.catalog.models.ResourceRelationship

class AvailableArtistRelationshipsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AvailableArtistRelationships
        //val modelInstance = AvailableArtistRelationships()

        // to test the property `similarArtists`
        should("test similarArtists") {
            // uncomment below to test the property
            //modelInstance.similarArtists shouldBe ("TODO")
        }

        // to test the property `albums`
        should("test albums") {
            // uncomment below to test the property
            //modelInstance.albums shouldBe ("TODO")
        }

        // to test the property `videos`
        should("test videos") {
            // uncomment below to test the property
            //modelInstance.videos shouldBe ("TODO")
        }

        // to test the property `tracks`
        should("test tracks") {
            // uncomment below to test the property
            //modelInstance.tracks shouldBe ("TODO")
        }

    }
}
