/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import generated.org.openapitools.client.models.AvailableAlbumRelationshipsItemsDataInner
import generated.org.openapitools.client.models.AvailableAlbumRelationshipsItemsDataInnerMeta

class AvailableAlbumRelationshipsItemsDataInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AvailableAlbumRelationshipsItemsDataInner
        //val modelInstance = AvailableAlbumRelationshipsItemsDataInner()

        // to test the property `id` - resource unique identifier
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type` - resource unique type
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `meta`
        should("test meta") {
            // uncomment below to test the property
            //modelInstance.meta shouldBe ("TODO")
        }

    }
}
