/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.AvailableVideoRelationships
import com.tidal.sdk.catalog.models.ResourceRelationship

class AvailableVideoRelationshipsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AvailableVideoRelationships
        //val modelInstance = AvailableVideoRelationships()

        // to test the property `albums`
        should("test albums") {
            // uncomment below to test the property
            //modelInstance.albums shouldBe ("TODO")
        }

        // to test the property `artists`
        should("test artists") {
            // uncomment below to test the property
            //modelInstance.artists shouldBe ("TODO")
        }

        // to test the property `providers`
        should("test providers") {
            // uncomment below to test the property
            //modelInstance.providers shouldBe ("TODO")
        }

    }
}
