/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import generated.org.openapitools.client.models.AvailableAlbumRelationshipsItems
import generated.org.openapitools.client.models.AvailableAlbumRelationshipsItemsDataInner
import generated.org.openapitools.client.models.Links

class AvailableAlbumRelationshipsItemsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AvailableAlbumRelationshipsItems
        //val modelInstance = AvailableAlbumRelationshipsItems()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `links`
        should("test links") {
            // uncomment below to test the property
            //modelInstance.links shouldBe ("TODO")
        }

    }
}
