/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.ErrorDocument
import com.tidal.sdk.catalog.models.ErrorObject
import com.tidal.sdk.catalog.models.Links

class ErrorDocumentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ErrorDocument
        //val modelInstance = ErrorDocument()

        // to test the property `errors` - array of error objects
        should("test errors") {
            // uncomment below to test the property
            //modelInstance.errors shouldBe ("TODO")
        }

        // to test the property `links`
        should("test links") {
            // uncomment below to test the property
            //modelInstance.links shouldBe ("TODO")
        }

    }
}
