/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import generated.org.openapitools.client.models.ErrorObject
import generated.org.openapitools.client.models.ErrorObjectSource

class ErrorObjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ErrorObject
        //val modelInstance = ErrorObject()

        // to test the property `id` - unique identifier for this particular occurrence of the problem
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `status` - HTTP status code applicable to this problem
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `code` - application-specific error code
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `detail` - human-readable explanation specific to this occurrence of the problem
        should("test detail") {
            // uncomment below to test the property
            //modelInstance.detail shouldBe ("TODO")
        }

        // to test the property `source`
        should("test source") {
            // uncomment below to test the property
            //modelInstance.source shouldBe ("TODO")
        }

    }
}
