/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.ErrorObjectSource

class ErrorObjectSourceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ErrorObjectSource
        //val modelInstance = ErrorObjectSource()

        // to test the property `pointer` - a JSON Pointer [RFC6901] to the value in the request document that caused the error
        should("test pointer") {
            // uncomment below to test the property
            //modelInstance.pointer shouldBe ("TODO")
        }

        // to test the property `parameter` - string indicating which URI query parameter caused the error.
        should("test parameter") {
            // uncomment below to test the property
            //modelInstance.parameter shouldBe ("TODO")
        }

        // to test the property `header` - string indicating the name of a single request header which caused the error
        should("test header") {
            // uncomment below to test the property
            //modelInstance.header shouldBe ("TODO")
        }

    }
}
