/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.ExternalLinkMeta

class ExternalLinkMetaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExternalLinkMeta
        //val modelInstance = ExternalLinkMeta()

        // to test the property `type` - external link type
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
