/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.ImageLink
import com.tidal.sdk.catalog.models.ImageLinkMeta

class ImageLinkTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ImageLink
        //val modelInstance = ImageLink()

        // to test the property `href` - link to an image
        should("test href") {
            // uncomment below to test the property
            //modelInstance.href shouldBe ("TODO")
        }

        // to test the property `meta`
        should("test meta") {
            // uncomment below to test the property
            //modelInstance.meta shouldBe ("TODO")
        }

    }
}
