/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import generated.org.openapitools.client.models.Links

class LinksTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Links
        //val modelInstance = Links()

        // to test the property `self` - the link that generated the current response document
        should("test self") {
            // uncomment below to test the property
            //modelInstance.self shouldBe ("TODO")
        }

        // to test the property `next` - the next page of data (pagination)
        should("test next") {
            // uncomment below to test the property
            //modelInstance.next shouldBe ("TODO")
        }

    }
}
