/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tidal.sdk.catalog.models.TrackDataDocument
import com.tidal.sdk.catalog.models.Links
import com.tidal.sdk.catalog.models.TrackRelationshipResource
import com.tidal.sdk.catalog.models.TrackResource

class TrackDataDocumentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrackDataDocument
        //val modelInstance = TrackDataDocument()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `links`
        should("test links") {
            // uncomment below to test the property
            //modelInstance.links shouldBe ("TODO")
        }

        // to test the property `included` - array of resource objects that are related to the primary data and/or each other
        should("test included") {
            // uncomment below to test the property
            //modelInstance.included shouldBe ("TODO")
        }

    }
}
