/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param `data`
 * @param links
 * @param included array of resource objects that are related to the primary data and/or each other
 */


data class AlbumDataDocument (

    @Json(name = "data")
    val `data`: AlbumResource,

    @Json(name = "links")
    val links: com.tidal.sdk.catalog.models.Links? = null,

    /* array of resource objects that are related to the primary data and/or each other */
    @Json(name = "included")
    val included: kotlin.collections.List<com.tidal.sdk.catalog.models.AlbumRelationshipResource>? = null

)
