/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 * document's primary data
 *
 * @param id resource unique identifier
 * @param type resource unique type
 * @param attributes
 * @param relationships
 * @param links
 */


data class AlbumResource (

    /* resource unique identifier */
    @Json(name = "id")
    val id: kotlin.String,

    /* resource unique type */
    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "attributes")
    val attributes: AlbumAttributes? = null,

    @Json(name = "relationships")
    val relationships: AvailableAlbumRelationships? = null,

    @Json(name = "links")
    val links: com.tidal.sdk.catalog.models.Links? = null

)
