/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param name Artist name
 * @param popularity Artist popularity (ranged in 0.00 ... 1.00). Conditionally visible
 * @param imageLinks Represents available links to, and metadata about, an artist images
 * @param externalLinks Represents available links to something that is related to an artist resource, but external to the TIDAL API
 */


data class ArtistAttributes (

    /* Artist name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Artist popularity (ranged in 0.00 ... 1.00). Conditionally visible */
    @Json(name = "popularity")
    val popularity: kotlin.Double,

    /* Represents available links to, and metadata about, an artist images */
    @Json(name = "imageLinks")
    val imageLinks: kotlin.collections.List<ImageLink>? = null,

    /* Represents available links to something that is related to an artist resource, but external to the TIDAL API */
    @Json(name = "externalLinks")
    val externalLinks: kotlin.collections.List<ExternalLink>? = null

)
