/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 * Available album relationships
 *
 * @param artists
 * @param similarAlbums
 * @param items
 * @param providers
 */


data class AvailableAlbumRelationships (

    @Json(name = "artists")
    val artists: ResourceRelationship? = null,

    @Json(name = "similarAlbums")
    val similarAlbums: ResourceRelationship? = null,

    @Json(name = "items")
    val items: AvailableAlbumRelationshipsItems? = null,

    @Json(name = "providers")
    val providers: ResourceRelationship? = null

)
