/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 * Available artist relationships
 *
 * @param similarArtists
 * @param albums
 * @param videos
 * @param tracks
 */


data class AvailableArtistRelationships (

    @Json(name = "similarArtists")
    val similarArtists: ResourceRelationship? = null,

    @Json(name = "albums")
    val albums: ResourceRelationship? = null,

    @Json(name = "videos")
    val videos: ResourceRelationship? = null,

    @Json(name = "tracks")
    val tracks: ResourceRelationship? = null

)
