/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 * Available video relationships
 *
 * @param albums
 * @param artists
 * @param providers
 */


data class AvailableVideoRelationships (

    @Json(name = "albums")
    val albums: com.tidal.sdk.catalog.models.ResourceRelationship? = null,

    @Json(name = "artists")
    val artists: com.tidal.sdk.catalog.models.ResourceRelationship? = null,

    @Json(name = "providers")
    val providers: com.tidal.sdk.catalog.models.ResourceRelationship? = null

)
