/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param id resource unique identifier
 * @param type resource unique type
 * @param meta
 */


data class AvailableAlbumRelationshipsItemsDataInner (

    /* resource unique identifier */
    @Json(name = "id")
    val id: kotlin.String,

    /* resource unique type */
    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "meta")
    val meta: AvailableAlbumRelationshipsItemsDataInnerMeta? = null

)
