/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models


import com.squareup.moshi.Json

/**
 *
 *
 * @param volumeNumber volume number
 * @param trackNumber track number
 */


data class AvailableAlbumRelationshipsItemsDataInnerMeta (

    /* volume number */
    @Json(name = "volumeNumber")
    val volumeNumber: kotlin.Int,

    /* track number */
    @Json(name = "trackNumber")
    val trackNumber: kotlin.Int

)
