/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param id unique identifier for this particular occurrence of the problem
 * @param status HTTP status code applicable to this problem
 * @param code application-specific error code
 * @param detail human-readable explanation specific to this occurrence of the problem
 * @param source
 */


data class ErrorObject (

    /* unique identifier for this particular occurrence of the problem */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* HTTP status code applicable to this problem */
    @Json(name = "status")
    val status: kotlin.String? = null,

    /* application-specific error code */
    @Json(name = "code")
    val code: kotlin.String? = null,

    /* human-readable explanation specific to this occurrence of the problem */
    @Json(name = "detail")
    val detail: kotlin.String? = null,

    @Json(name = "source")
    val source: com.tidal.sdk.catalog.models.ErrorObjectSource? = null

)
