/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param errors array of error objects
 * @param links
 */


data class ErrorDocument (

    /* array of error objects */
    @Json(name = "errors")
    val errors: kotlin.collections.List<ErrorObject>? = null,

    @Json(name = "links")
    val links: com.tidal.sdk.catalog.models.Links? = null

)
