/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * metadata about an external link
 *
 * @param type external link type
 */


data class ExternalLinkMeta (

    /* external link type */
    @Json(name = "type")
    val type: com.tidal.sdk.catalog.models.ExternalLinkMeta.Type

) {

    /**
     * external link type
     *
     * Values: TIDAL_SHARING,TIDAL_AUTOPLAY_ANDROID,TIDAL_AUTOPLAY_IOS,TIDAL_AUTOPLAY_WEB,TWITTER,FACEBOOK,INSTAGRAM,TIKTOK,SNAPCHAT,HOMEPAGE
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "TIDAL_SHARING") TIDAL_SHARING("TIDAL_SHARING"),
        @Json(name = "TIDAL_AUTOPLAY_ANDROID") TIDAL_AUTOPLAY_ANDROID("TIDAL_AUTOPLAY_ANDROID"),
        @Json(name = "TIDAL_AUTOPLAY_IOS") TIDAL_AUTOPLAY_IOS("TIDAL_AUTOPLAY_IOS"),
        @Json(name = "TIDAL_AUTOPLAY_WEB") TIDAL_AUTOPLAY_WEB("TIDAL_AUTOPLAY_WEB"),
        @Json(name = "TWITTER") TWITTER("TWITTER"),
        @Json(name = "FACEBOOK") FACEBOOK("FACEBOOK"),
        @Json(name = "INSTAGRAM") INSTAGRAM("INSTAGRAM"),
        @Json(name = "TIKTOK") TIKTOK("TIKTOK"),
        @Json(name = "SNAPCHAT") SNAPCHAT("SNAPCHAT"),
        @Json(name = "HOMEPAGE") HOMEPAGE("HOMEPAGE");
    }
}
