/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param href link to an image
 * @param meta
 */


data class ImageLink (

    /* link to an image */
    @Json(name = "href")
    val href: kotlin.String,

    @Json(name = "meta")
    val meta: com.tidal.sdk.catalog.models.ImageLinkMeta

)
