/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models


import com.squareup.moshi.Json

/**
 * links object
 *
 * @param self the link that generated the current response document
 * @param next the next page of data (pagination)
 */


data class Links (

    /* the link that generated the current response document */
    @Json(name = "self")
    val self: kotlin.String,

    /* the next page of data (pagination) */
    @Json(name = "next")
    val next: kotlin.String? = null

)
