/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models


import com.squareup.moshi.Json

/**
 *
 *
 * @param name Provider name. Conditionally visible.
 */


data class ProviderAttributes (

    /* Provider name. Conditionally visible. */
    @Json(name = "name")
    val name: kotlin.String

)
