/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param `data` resource linkage
 * @param links
 */


data class ResourceRelationship (

    /* resource linkage */
    @Json(name = "data")
    val `data`: kotlin.collections.List<ResourceIdentifier>? = null,

    @Json(name = "links")
    val links: com.tidal.sdk.catalog.models.Links? = null

)
