/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param title Album item's title
 * @param isrc ISRC code
 * @param duration Duration expressed in accordance with ISO 8601
 * @param explicit Indicates whether a catalog item consist of any explicit content
 * @param popularity Track or video popularity (ranged in 0.00 ... 1.00). Conditionally visible
 * @param mediaTags
 * @param version Version of the album's item; complements title
 * @param copyright Copyright information
 * @param availability Defines a catalog item availability e.g. for streaming, DJs, stems
 * @param externalLinks Represents available links to something that is related to a catalog item, but external to the TIDAL API
 */


data class TrackAttributes (

    /* Album item's title */
    @Json(name = "title")
    val title: kotlin.String,

    /* ISRC code */
    @Json(name = "isrc")
    val isrc: kotlin.String,

    /* Duration expressed in accordance with ISO 8601 */
    @Json(name = "duration")
    val duration: kotlin.String,

    /* Indicates whether a catalog item consist of any explicit content */
    @Json(name = "explicit")
    val explicit: kotlin.Boolean,

    /* Track or video popularity (ranged in 0.00 ... 1.00). Conditionally visible */
    @Json(name = "popularity")
    val popularity: kotlin.Double,

    @Json(name = "mediaTags")
    val mediaTags: kotlin.collections.List<kotlin.String>,

    /* Version of the album's item; complements title */
    @Json(name = "version")
    val version: kotlin.String? = null,

    /* Copyright information */
    @Json(name = "copyright")
    val copyright: kotlin.String? = null,

    /* Defines a catalog item availability e.g. for streaming, DJs, stems */
    @Json(name = "availability")
    val availability: kotlin.collections.List<TrackAttributes.Availability>? = null,

    /* Represents available links to something that is related to a catalog item, but external to the TIDAL API */
    @Json(name = "externalLinks")
    val externalLinks: kotlin.collections.List<ExternalLink>? = null

) {

    /**
     * Defines a catalog item availability e.g. for streaming, DJs, stems
     *
     * Values: STREAM,DJ,STEM
     */
    @JsonClass(generateAdapter = false)
    enum class Availability(val value: kotlin.String) {
        @Json(name = "STREAM") STREAM("STREAM"),
        @Json(name = "DJ") DJ("DJ"),
        @Json(name = "STEM") STEM("STEM");
    }
}
