/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tidal.sdk.catalog.models


import com.squareup.moshi.Json

/**
 * metadata about a video
 *
 * @param width video width (in pixels)
 * @param height video height (in pixels)
 */


data class VideoLinkMeta (

    /* video width (in pixels) */
    @Json(name = "width")
    val width: kotlin.Int,

    /* video height (in pixels) */
    @Json(name = "height")
    val height: kotlin.Int

)
