# Automated Release Creation and Publishing
#
# This workflow is triggered by post-merge.yml when version changes are detected
# in module gradle.properties files. It automatically:
# 1. Creates a release with the new version tag
# 2. Publishes the release
# 3. Triggers publish-release.yml to publish packages to Maven Central
name: Create release

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
    secrets:
      pat:
        required: true

jobs:
  expose-tag:
    name: Expose Tag
    runs-on: ubuntu-latest
    outputs:
      module-tag: ${{ steps.expose-tag.outputs.tag }}
      module-version: ${{ steps.expose-tag.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Expose tag and version
        id: expose-tag
        run: |
          version="$(./gradlew ${{ inputs.module }}:properties | grep "^version: " | awk '{print $2}')"
          tag="${{ inputs.module }}-$version"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT

  create-and-publish-release:
    runs-on: ubuntu-latest
    needs: [ expose-tag ]
    permissions: 
      contents: write
    env: 
      name: ${{ inputs.module}}
      version: ${{ needs.expose-tag.outputs.module-version}}
      tag: ${{ needs.expose-tag.outputs.module-tag}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin

    - name: Extract changelog content
      id: changelog
      run: |
        changelog_file="${{ env.name }}/CHANGELOG.md"
        version_section=$(awk "/^## \[${{ env.version }}\]/{flag=1; next} /^## \[/{flag=0} flag" "$changelog_file")
        echo "$version_section" > /tmp/changelog_content.md

    - name: Create and publish release
      id: create-release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.tag }}
        name: ${{ env.tag }}
        bodyFile: /tmp/changelog_content.md
        draft: false
        prerelease: false
        allowUpdates: false
