name: Create release

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
    secrets:
      pat:
        required: true

jobs:
  expose-tag:
    name: Expose Tag
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubToken: ${{ secrets.pat }}
    outputs:
      module-tag: ${{ steps.expose-tag.outputs.tag }}
      module-version: ${{ steps.expose-tag.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Expose tag and version
        id: expose-tag
        run: |
          version="$(./gradlew ${{ inputs.module }}:properties | grep "^version: " | awk '{print $2}')"
          tag="${{ inputs.module }}-$version"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT
  
  create-release:
    runs-on: ubuntu-latest
    needs: [ expose-tag ]
    permissions: 
      contents: write
    env: 
      name: ${{ inputs.module}}
      version: ${{ needs.expose-tag.outputs.module-version}}
      tag: ${{ needs.expose-tag.outputs.module-tag}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin

    - name: Generate Release Draft
      id: generate-release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.tag }}  
        allowUpdates: true
        draft: true
        body: "This is a release draft for ${{ env.tag }}"
