name: FOSSA Scans

on:
  workflow_call:
    secrets:
      pat:
        required: true
      fossaApiKey:
        required: true
env:
  ORG_GRADLE_PROJECT_githubToken: ${{ secrets.pat }}

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v3
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@v1.3.3
        with:
          api-key: ${{secrets.fossaApiKey}}

      - name: "Run FOSSA Tests"
        uses: fossas/fossa-action@v1.3.3
        with:
          api-key: ${{secrets.fossaApiKey}}
          run-tests: true
