name: FOSSA Scans

on:
  workflow_call:
    secrets:
      pat:
        required: true
      fossaApiKey:
        required: true

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v3
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac
        with:
          api-key: ${{secrets.fossaApiKey}}

      - name: "Run FOSSA Tests"
        uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac
        with:
          api-key: ${{secrets.fossaApiKey}}
          run-tests: true
