name: Run lint checks

on:
  workflow_call:
    secrets:
      pat:
        required: true

jobs:
  run-ktfmt:
    runs-on: ubuntu-latest
    name: Run ktfmt
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Run ktfmt
        run: static-analysis/run-ktfmt.sh -l

  run-detekt:
    runs-on: ubuntu-latest
    name: Run detekt
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Run detekt
        run: static-analysis/run-detekt.sh

  run-lint:
    runs-on: ubuntu-latest
    name: Run lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Run lint
        run: ./gradlew lint

      - name: Print lint report(s)
        if: ${{ failure() }}
        run: cat **/build/reports/lint-results-*.xml
