name: Publish release

on:
  release:
    types: [published]

env:
  ORG_GRADLE_PROJECT_githubToken: ${{ secrets.PACKAGES_PAT }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92
      - name: Get module name
        id: get-name
        run: |
          ref="${{ github.ref}}"
          name="$( echo ${ref##*/} | cut -d- -f1 )"
          echo "name=$name" >> $GITHUB_OUTPUT
      - name: Publish package
        run: |
          ./gradlew publish-sdk-module-${{ env.NAME }} --continue
        env:
          NAME: ${{ steps.get-name.outputs.name }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SIGNING_IN_MEMORY_KEY }}

  deploy-pages:
    name: Trigger GH Pages deployment
    if: startsWith(github.ref, 'refs/tags/bom-')
    permissions:
      contents: read # TODO remove when the repository goes public
      pages: write
      id-token: write
    uses: ./.github/workflows/publish-pages.yml
    secrets: inherit
