name: Publish release

on:
  release:
    types: [ published ]

jobs:
  deploy-pages:
    name: Trigger GH Pages deployment
    if: startsWith(github.ref, 'refs/tags/bom-')
    permissions:
      pages: write
      id-token: write
    uses: ./.github/workflows/publish-pages.yml
    secrets: inherit
